moveit_config_pkg: iiwa_moveit_config
move_group: iiwa_arm
sample_size: 10000

ik_solvers:
  ik_solver_1:
    name: KDL
    kinematics_file: kdl_kinematics.yaml
  ik_solver_2:
    name: TRAC_IK
    kinematics_file: trac_ik_kinematics.yaml
  ik_solver_3:
    name: pick_ik
    kinematics_file: pick_ik_kinematics.yaml
