moveit_config_pkg: moveit_resources_panda_moveit_config
robot_name: panda 
planning_group: panda_arm
sample_size: 10000

ik_solvers:
  - name: KDL
    kinematics_file: kdl_kinematics.yaml
    
  - name: TRAC_IK
    kinematics_file: trac_ik_kinematics.yaml
  
  - name: pick_ik
    kinematics_file: pick_ik_kinematics.yaml
